### ISSUE TITLE
rotate image

### ISSUE THREAD

**Issue by parvu** [PX4/snap_cam#3]
Hi,
Please hep
I have installed the ROS_snap_cam on Snapdragon flight board and the image from the highres in 90 deg rotated. Is there any fix ? Thank you

**Comment by ChristophTobler** [comment]
One of our boards just had the same problem... I'll have a look at it.

**Comment by ChristophTobler** [comment]
The problem is that the image sensor is mounted the wrong way. You can rotate the image in the node (see below), but the image will still be the wrong format (height is bigger than width). So you can either make the changes in "snap_cam_publisher_node.cpp" or try to correct it in hardware.

void rot90(cv::Mat &matImage, int rotflag){
  //1=CW, 2=CCW, 3=180
  if (rotflag == 1){
    cv::transpose(matImage, matImage);
    cv::flip(matImage, matImage,1); //transpose+flip(1)=CW
  } else if (rotflag == 2) {
    cv::transpose(matImage, matImage);
    cv::flip(matImage, matImage,0); //transpose+flip(0)=CCW
  } else if (rotflag ==3){
    cv::flip(matImage, matImage,-1);    //flip(-1)=180
  } else if (rotflag != 0){ //if not 0,1,2,3:
    cout  << "Unknown rotation flag(" << rotflag << ")" << endl;
  }
}

void imageCallback(const cv::Mat &img, uint64_t time_stamp)
{
    // convert OpenCV image to ROS message
    cv::Mat img_ = img;
    rot90(img_,2);
    cv_bridge::CvImage cvi;
    cvi.header.stamp = ros::Time::now();
    cvi.header.frame_id = "image";
    cvi.image = img_;

```
if (img.channels() == 1) { // optical flow
    cvi.encoding = "mono8";

} else { // highres
    cvi.encoding = "bgr8";
}

sensor_msgs::Image im;
cvi.toImageMsg(im);
image_pub.publish(im);
```

}

**Comment by parvu** [comment]
It seems that imx214 camera is not only wrong mounted but uses rgb8 encoding. 
change: 
cvi.encoding = "bgr8"; in cvi.encoding = "rgb8";
if this is your case

**Comment by SamChenzx** [comment]
@parvu and @ChristophTobler I have installed ROS both in snapdragon flight and my VM Ubuntu Linux, when I start the node by `roslaunch snap_cam <CAM>.launch`, I can find the topic in my VM, but can't show on screen by `rosrun image_view image_view image:=/snap_cam_highres_publisher/image`, how do you show your image on screen?
